openapi: 3.1.0
info:
  version: 1.0.0
  title: E-monitoring
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of energy monitoring application
tags:
  - name: Green
    description: Operations about Green Plants.
  - name: Thermal
    description: Operations about Thermal Plants.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://energy-monitoring.onrender.com
paths:
  /green:
    get:
      $ref: ../src/swagger/paths/green/get.yaml
    post:
      $ref: ../src/swagger/paths/green/post.yaml
  /green/{id}:
    get:
      $ref: ../src/swagger/paths/green/{id}/get.yaml
  /thermal:
    get:
      $ref: ../src/swagger/paths/thermal/get.yaml
    post:
      $ref: ../src/swagger/paths/thermal/post.yaml
  /thermal/{id}:
    get:
      $ref: ../src/swagger/paths/thermal/{id}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
